/**
 * FxRate
 *
 * @author Afaan Bilal
 * @link   https://afaan.dev
 *
 * @copyright 2024 Afaan Bilal
 */

export default [
    { code: "inr", label: "Indian Rupee" },
    { code: "usd", label: "US Dollar" },
    { code: "eur", label: "Euro" },
    { code: "sar", label: "Saudi Arabian Riyal" },
    { code: "aed", label: "Emirati Dirham" },
    { code: "trl", label: "Turkish Lira" },
    { code: "jpy", label: "Japanese Yen" },
    { code: "gbp", label: "British Pound" },
    { code: "aud", label: "Australian Dollar" },
    { code: "cad", label: "Canadian Dollar" },
    { code: "chf", label: "Swiss Franc" },
    { code: "cnh", label: "Chinese Yuan Renminbi Offshore" },
    { code: "cny", label: "Chinese Yuan Renminbi" },
    { code: "hkd", label: "Hong Kong Dollar" },
    { code: "nzd", label: "New Zealand Dollar" },
    { code: "rub", label: "Russian Ruble" },
    { code: "idr", label: "Indonesian Rupiah" },
    { code: "pkr", label: "Pakistani Rupee" },

    { code: "aave", label: "Aave" },
    { code: "abt", label: "Arcblock" },
    { code: "ach", label: "Alchemy Pay" },
    { code: "acs", label: "ACryptoS" },
    { code: "ada", label: "Cardano" },
    { code: "aergo", label: "Aergo" },
    { code: "afn", label: "Afghan Afghani" },
    { code: "agix", label: "SingularityNET" },
    { code: "agld", label: "Adventure Gold" },
    { code: "aioz", label: "Aioz Network" },
    { code: "akt", label: "Akash Network" },
    { code: "alcx", label: "Alchemix" },
    { code: "aleph", label: "Aleph.im" },
    { code: "alex", label: "Alexandrite" },
    { code: "algo", label: "Algorand" },
    { code: "alice", label: "My Neighbor Alice" },
    { code: "all", label: "Albanian Lek" },
    { code: "alph", label: "Alephium" },
    { code: "alusd", label: "Alchemix USD" },
    { code: "amd", label: "Armenian Dram" },
    { code: "amp", label: "Amp" },
    { code: "ang", label: "Dutch Guilder" },
    { code: "ankr", label: "Ankr Network" },
    { code: "ant", label: "Aragon" },
    { code: "aoa", label: "Angolan Kwanza" },
    { code: "ape", label: "ApeCoin" },
    { code: "api3", label: "API3" },
    { code: "apt", label: "Aptos" },
    { code: "ar", label: "Arweave" },
    { code: "arb", label: "Arbitrum" },
    { code: "arpa", label: "ARPA Chain" },
    { code: "ars", label: "Argentine Peso" },
    { code: "asm", label: "Assemble Protocol" },
    { code: "ast", label: "AirSwap" },
    { code: "astr", label: "Astar" },
    { code: "ata", label: "Automata Network" },
    { code: "atom", label: "Cosmos" },
    { code: "ats", label: "Austrian Schilling" },
    { code: "auction", label: "Bounce Token AUCTION" },
    { code: "audio", label: "Audius" },
    { code: "aurora", label: "Aurora" },
    { code: "avax", label: "Avalanche" },
    { code: "avt", label: "Aventus" },
    { code: "awg", label: "Aruban or Dutch Guilder" },
    { code: "axl", label: "Axelar" },
    { code: "axs", label: "Axie Infinity" },
    { code: "azero", label: "Aleph Zero" },
    { code: "azm", label: "Azerbaijani Manat" },
    { code: "azn", label: "Azerbaijan Manat" },
    { code: "babydoge", label: "BabyDoge ETH" },
    { code: "badger", label: "Badger DAO" },
    { code: "bake", label: "BakeryToken" },
    { code: "bal", label: "Balancer" },
    { code: "bam", label: "Bosnian Convertible Mark" },
    { code: "band", label: "Band Protocol" },
    { code: "bat", label: "Basic Attention Token" },
    { code: "bbd", label: "Barbadian or Bajan Dollar" },
    { code: "bch", label: "Bitcoin Cash" },
    { code: "bdt", label: "Bangladeshi Taka" },
    { code: "bdx", label: "Beldex" },
    { code: "beam", label: "Beam" },
    { code: "bef", label: "Belgian Franc" },
    { code: "bgb", label: "Bitget Token" },
    { code: "bgn", label: "Bulgarian Lev" },
    { code: "bhd", label: "Bahraini Dinar" },
    { code: "bico", label: "Biconomy" },
    { code: "bif", label: "Burundian Franc" },
    { code: "bit", label: "BitDAO" },
    { code: "blur", label: "Blur" },
    { code: "blz", label: "Bluzelle" },
    { code: "bmd", label: "Bermudian Dollar" },
    { code: "bnb", label: "Binance Coin" },
    { code: "bnd", label: "Bruneian Dollar" },
    { code: "bnt", label: "Bancor Network" },
    { code: "bob", label: "Bolivian Bolíviano" },
    { code: "boba", label: "Boba Network" },
    { code: "bond", label: "BarnBridge" },
    { code: "brl", label: "Brazilian Real" },
    { code: "bsd", label: "Bahamian Dollar" },
    { code: "bsv", label: "Bitcoin SV" },
    { code: "bsw", label: "Biswap" },
    { code: "btc", label: "Bitcoin" },
    { code: "btcb", label: "Bitcoin BEP2" },
    { code: "btg", label: "Bitcoin Gold" },
    { code: "btn", label: "Bhutanese Ngultrum" },
    { code: "btrst", label: "Braintrust" },
    { code: "btt", label: "BitTorrent" },
    { code: "busd", label: "Binance USD" },
    { code: "bwp", label: "Botswana Pula" },
    { code: "byn", label: "Belarusian Ruble" },
    { code: "byr", label: "Belarusian Ruble" },
    { code: "bzd", label: "Belizean Dollar" },
    { code: "c98", label: "Coin98" },
    { code: "cake", label: "PancakeSwap" },
    { code: "cbeth", label: "Coinbase Wrapped Staked ETH" },
    { code: "cdai", label: "Compound Dai" },
    { code: "cdf", label: "Congolese Franc" },
    { code: "cdt", label: "Blox" },
    { code: "celo", label: "Celo" },
    { code: "celr", label: "Celer Network" },
    { code: "cfg", label: "Centrifuge" },
    { code: "cfx", label: "Conflux" },
    { code: "cgld", label: "Celo Gold" },
    { code: "chr", label: "Chromia" },
    { code: "chz", label: "Chiliz" },
    { code: "clp", label: "Chilean Peso" },
    { code: "clv", label: "Clover Finance" },
    { code: "comp", label: "Compound" },
    { code: "cop", label: "Colombian Peso" },
    { code: "core", label: "Core Group Asset" },
    { code: "coti", label: "COTI" },
    { code: "coval", label: "COVAL" },
    { code: "cqt", label: "Covalent" },
    { code: "crc", label: "Costa Rican Colon" },
    { code: "cro", label: "Crypto.com Chain" },
    { code: "crpt", label: "Crypterium" },
    { code: "crv", label: "Curve DAO Token" },
    { code: "cspr", label: "Casper" },
    { code: "ctc", label: "CarterCoin" },
    { code: "ctsi", label: "Cartesi" },
    { code: "ctx", label: "Cryptex Finance" },
    { code: "cuc", label: "Cuban Convertible Peso" },
    { code: "cup", label: "Cuban Peso" },
    { code: "cvc", label: "Civic" },
    { code: "cve", label: "Cape Verdean Escudo" },
    { code: "cvx", label: "Convex Finance" },
    { code: "cyp", label: "Cypriot Pound" },
    { code: "czk", label: "Czech Koruna" },
    { code: "dag", label: "Constellation" },
    { code: "dai", label: "DAI" },
    { code: "dao", label: "DAO Maker" },
    { code: "dar", label: "Mines of Dalarnia" },
    { code: "dash", label: "Digital Cash" },
    { code: "dcr", label: "Decred" },
    { code: "ddx", label: "DerivaDAO" },
    { code: "dem", label: "German Deutsche Mark" },
    { code: "deso", label: "Decentralized Social" },
    { code: "dexe", label: "DeXe" },
    { code: "dext", label: "DEXTools" },
    { code: "dfi", label: "DfiStarter" },
    { code: "dia", label: "Dia" },
    { code: "dimo", label: "DIMO" },
    { code: "djf", label: "Djiboutian Franc" },
    { code: "dkk", label: "Danish Krone" },
    { code: "dnt", label: "District0x" },
    { code: "doge", label: "Dogecoin" },
    { code: "dop", label: "Dominican Peso" },
    { code: "dot", label: "Polkadot" },
    { code: "drep", label: "Drep [new]" },
    { code: "dydx", label: "dYdX" },
    { code: "dyp", label: "DeFi Yield Protocol" },
    { code: "dzd", label: "Algerian Dinar" },
    { code: "edu", label: "EduCoin" },
    { code: "eek", label: "Estonian Kroon" },
    { code: "egld", label: "Elrond" },
    { code: "egp", label: "Egyptian Pound" },
    { code: "ela", label: "Elastos" },
    { code: "elf", label: "aelf" },
    { code: "elg", label: "EscoinToken" },
    { code: "enj", label: "Enjin Coin" },
    { code: "ens", label: "Ethereum Name Service" },
    { code: "eos", label: "EOS" },
    { code: "ern", label: "Eritrean Nakfa" },
    { code: "esp", label: "Spanish Peseta" },
    { code: "etb", label: "Ethiopian Birr" },
    { code: "etc", label: "Ethereum Classic" },
    { code: "eth", label: "Ethereum" },
    { code: "eth2", label: "Ethereum 2.0" },
    { code: "euroc", label: "Euro Coin" },
    { code: "ever", label: "EverLife.AI" },
    { code: "farm", label: "Harvest Finance" },
    { code: "fei", label: "Fei USD" },
    { code: "fet", label: "Fetch.ai" },
    { code: "fida", label: "Bonfida" },
    { code: "fil", label: "Filecoin" },
    { code: "fim", label: "Finnish Markka" },
    { code: "fis", label: "Stafi" },
    { code: "fjd", label: "Fijian Dollar" },
    { code: "fkp", label: "Falkland Island Pound" },
    { code: "floki", label: "Baby Moon Floki" },
    { code: "flow", label: "Flow" },
    { code: "flr", label: "FLARE" },
    { code: "flux", label: "Datamine FLUX" },
    { code: "fort", label: "Forta" },
    { code: "forth", label: "Ampleforth Governance Token" },
    { code: "fox", label: "Shapeshift FOX Token" },
    { code: "frax", label: "Frax" },
    { code: "frf", label: "French Franc" },
    { code: "ftm", label: "Fantom" },
    { code: "ftt", label: "FarmaTrust" },
    { code: "fx", label: "Function X" },
    { code: "fxs", label: "Frax Share" },
    { code: "gal", label: "Project Galaxy" },
    { code: "gala", label: "Gala" },
    { code: "gas", label: "Gas" },
    { code: "gel", label: "Georgian Lari" },
    { code: "gfi", label: "Goldfinch" },
    { code: "ggp", label: "Guernsey Pound" },
    { code: "ghc", label: "Ghanaian Cedi" },
    { code: "ghs", label: "Ghanaian Cedi" },
    { code: "ghst", label: "Aavegotchi" },
    { code: "gip", label: "Gibraltar Pound" },
    { code: "glm", label: "Golem" },
    { code: "glmr", label: "Moonbeam" },
    { code: "gmd", label: "Gambian Dalasi" },
    { code: "gmt", label: "Stepn" },
    { code: "gmx", label: "Goldmaxcoin" },
    { code: "gnf", label: "Guinean Franc" },
    { code: "gno", label: "Gnosis" },
    { code: "gns", label: "Gains Network" },
    { code: "gnt", label: "GreenTrust" },
    { code: "gods", label: "Gods Unchained" },
    { code: "grd", label: "Greek Drachma" },
    { code: "grt", label: "The Graph" },
    { code: "gst", label: "Green Satoshi Token" },
    { code: "gt", label: "GateToken" },
    { code: "gtc", label: "Gitcoin" },
    { code: "gtq", label: "Guatemalan Quetzal" },
    { code: "gusd", label: "Gemini US Dollar" },
    { code: "gyd", label: "Guyanese Dollar" },
    { code: "gyen", label: "GYEN" },
    { code: "hbar", label: "Hedera" },
    { code: "hbtc", label: "Huobi BTC" },
    { code: "hft", label: "Hashflow" },
    { code: "high", label: "Highstreet" },
    { code: "hnl", label: "Honduran Lempira" },
    { code: "hnt", label: "Helium" },
    { code: "hopr", label: "HOPR" },
    { code: "hot", label: "Hydro Protocol" },
    { code: "hrk", label: "Croatian Kuna" },
    { code: "ht", label: "Huobi Token" },
    { code: "htg", label: "Haitian Gourde" },
    { code: "huf", label: "Hungarian Forint" },
    { code: "icp", label: "Internet Computer" },
    { code: "icx", label: "ICON Project" },
    { code: "idex", label: "IDEX" },
    { code: "iep", label: "Irish Pound" },
    { code: "ils", label: "Israeli Shekel" },
    { code: "ilv", label: "Illuvium" },
    { code: "imp", label: "Isle of Man Pound" },
    { code: "imx", label: "Immutable X" },
    { code: "index", label: "Index Cooperative" },
    { code: "inj", label: "Injective" },
    { code: "inv", label: "Inverse Finance" },
    { code: "iost", label: "IOS token" },
    { code: "iotx", label: "IoTeX" },
    { code: "iqd", label: "Iraqi Dinar" },
    { code: "irr", label: "Iranian Rial" },
    { code: "isk", label: "Icelandic Krona" },
    { code: "itl", label: "Italian Lira" },
    { code: "jasmy", label: "Jasmy" },
    { code: "jep", label: "Jersey Pound" },
    { code: "jmd", label: "Jamaican Dollar" },
    { code: "jod", label: "Jordanian Dinar" },
    { code: "joe", label: "JOE" },
    { code: "jst", label: "JUST" },
    { code: "jup", label: "Jupiter" },
    { code: "kava", label: "Kava" },
    { code: "kcs", label: "Kucoin" },
    { code: "kda", label: "Kadena" },
    { code: "keep", label: "Keep Network" },
    { code: "kes", label: "Kenyan Shilling" },
    { code: "kgs", label: "Kyrgyzstani Som" },
    { code: "khr", label: "Cambodian Riel" },
    { code: "klay", label: "Klaytn" },
    { code: "kmf", label: "Comorian Franc" },
    { code: "knc", label: "Kyber Network Crystals" },
    { code: "kpw", label: "North Korean Won" },
    { code: "krl", label: "Kryll" },
    { code: "krw", label: "South Korean Won" },
    { code: "ksm", label: "Kusama" },
    { code: "kub", label: "Bitkub Coin" },
    { code: "kuji", label: "Kujira" },
    { code: "kwd", label: "Kuwaiti Dinar" },
    { code: "kyd", label: "Caymanian Dollar" },
    { code: "kzt", label: "Kazakhstani Tenge" },
    { code: "lak", label: "Lao Kip" },
    { code: "lbp", label: "Lebanese Pound" },
    { code: "lcx", label: "LCX" },
    { code: "ldo", label: "Lido DAO Token" },
    { code: "leo", label: "LEOcoin" },
    { code: "link", label: "Chainlink" },
    { code: "lit", label: "Litentry" },
    { code: "lkr", label: "Sri Lankan Rupee" },
    { code: "loka", label: "League of Kingdoms Arena" },
    { code: "loom", label: "Loom Network" },
    { code: "lpt", label: "Livepeer (LPT)" },
    { code: "lqty", label: "Liquity" },
    { code: "lrc", label: "Loopring" },
    { code: "lrd", label: "Liberian Dollar" },
    { code: "lseth", label: "Liquid Staked Ethereum" },
    { code: "lsk", label: "Lisk" },
    { code: "lsl", label: "Basotho Loti" },
    { code: "ltc", label: "Litecoin" },
    { code: "ltl", label: "Lithuanian Litas" },
    { code: "luf", label: "Luxembourg Franc" },
    { code: "luna", label: "Terra" },
    { code: "lusd", label: "Limited USD" },
    { code: "lvl", label: "Latvian Lat" },
    { code: "lyd", label: "Libyan Dinar" },
    { code: "lyxe", label: "LUKSO" },
    { code: "mad", label: "Moroccan Dirham" },
    { code: "magic", label: "MAGIC" },
    { code: "mana", label: "Mana Coin Decentraland" },
    { code: "mask", label: "Mask Network" },
    { code: "math", label: "MATH" },
    { code: "matic", label: "Polygon" },
    { code: "mbx", label: "MobieCoin" },
    { code: "mco2", label: "Moss Carbon Credit" },
    { code: "mdl", label: "Moldovan Leu" },
    { code: "mdt", label: "Measurable Data Token" },
    { code: "media", label: "Media Network" },
    { code: "meme", label: "Pepe" },
    { code: "metis", label: "MetisDAO" },
    { code: "mga", label: "Malagasy Ariary" },
    { code: "mgf", label: "Malagasy Franc" },
    { code: "mina", label: "Mina" },
    { code: "mir", label: "Mirror Protocol" },
    { code: "mkd", label: "Macedonian Denar" },
    { code: "mkr", label: "Maker" },
    { code: "mln", label: "Enzyme" },
    { code: "mmk", label: "Burmese Kyat" },
    { code: "mnde", label: "Marinade" },
    { code: "mnt", label: "Mongolian Tughrik" },
    { code: "mona", label: "Monavale" },
    { code: "mop", label: "Macau Pataca" },
    { code: "movr", label: "Moonriver" },
    { code: "mpl", label: "Maple" },
    { code: "mro", label: "Mauritanian Ouguiya" },
    { code: "mru", label: "Mauritanian Ouguiya" },
    { code: "msol", label: "Marinade Staked SOL" },
    { code: "mtl", label: "Maltese Lira" },
    { code: "multi", label: "Multichain" },
    { code: "mur", label: "Mauritian Rupee" },
    { code: "musd", label: "mStableUSD" },
    { code: "muse", label: "Muse" },
    { code: "mvr", label: "Maldivian Rufiyaa" },
    { code: "mwk", label: "Malawian Kwacha" },
    { code: "mx", label: "MarsX" },
    { code: "mxc", label: "MXC" },
    { code: "mxn", label: "Mexican Peso" },
    { code: "myr", label: "Malaysian Ringgit" },
    { code: "mzm", label: "Mozambican Metical" },
    { code: "mzn", label: "Mozambican Metical" },
    { code: "nad", label: "Namibian Dollar" },
    { code: "nct", label: "Polyswarm" },
    { code: "near", label: "NEAR Protocol" },
    { code: "neo", label: "NEO" },
    { code: "nest", label: "NEST Protocol" },
    { code: "nexo", label: "NEXO" },
    { code: "nft", label: "NFT" },
    { code: "ngn", label: "Nigerian Naira" },
    { code: "nio", label: "Nicaraguan Cordoba" },
    { code: "nkn", label: "NKN" },
    { code: "nlg", label: "Dutch Guilder" },
    { code: "nmr", label: "Numeraire Network" },
    { code: "nok", label: "Norwegian Krone" },
    { code: "npr", label: "Nepalese Rupee" },
    { code: "ntrn", label: "Neutron" },
    { code: "nu", label: "NuCypher" },
    { code: "nxm", label: "NXM" },
    { code: "ocean", label: "Ocean Protocol" },
    { code: "ogn", label: "Origin Token" },
    { code: "ohm", label: "Olympus v1" },
    { code: "okb", label: "Okex" },
    { code: "okt", label: "OEC Token" },
    { code: "omg", label: "Omisego" },
    { code: "omi", label: "ECOMI" },
    { code: "omr", label: "Omani Rial" },
    { code: "one", label: "Menlo One" },
    { code: "ont", label: "Ontology" },
    { code: "ooki", label: "Ooki Protocol" },
    { code: "op", label: "Optimism" },
    { code: "orca", label: "Orca" },
    { code: "orn", label: "Orion Protocol" },
    { code: "osmo", label: "Osmosis" },
    { code: "oxt", label: "Orchid Network" },
    { code: "pab", label: "Panamanian Balboa" },
    { code: "pax", label: "Paxos Standard Token" },
    { code: "paxg", label: "PAX Gold" },
    { code: "pen", label: "Peruvian Sol" },
    { code: "people", label: "ConstitutionDAO" },
    { code: "perp", label: "Perpetual Protocol" },
    { code: "pgk", label: "Papua New Guinean Kina" },
    { code: "php", label: "Philippine Peso" },
    { code: "pla", label: "PlayDapp" },
    { code: "pln", label: "Polish Zloty" },
    { code: "plu", label: "Pluton" },
    { code: "png", label: "Pangolin" },
    { code: "pokt", label: "Pocket Network" },
    { code: "pols", label: "Polkastarter" },
    { code: "poly", label: "Polymath" },
    { code: "pond", label: "Marlin" },
    { code: "powr", label: "Powerledger" },
    { code: "prime", label: "Echelon Prime" },
    { code: "pro", label: "Propy" },
    { code: "prq", label: "PARSIQ" },
    { code: "pte", label: "Portuguese Escudo" },
    { code: "pundix", label: "Pundi X (New)" },
    { code: "pyg", label: "Paraguayan Guarani" },
    { code: "pyr", label: "Vulcan Forged PYR" },
    { code: "qar", label: "Qatari Riyal" },
    { code: "qi", label: "BENQI" },
    { code: "qnt", label: "Quant" },
    { code: "qsp", label: "Quantstamp" },
    { code: "qtum", label: "QTUM" },
    { code: "quick", label: "QuickSwap" },
    { code: "rad", label: "Radicle" },
    { code: "rai", label: "Rai Reflex Index" },
    { code: "rare", label: "SuperRare" },
    { code: "rari", label: "Rarible" },
    { code: "ray", label: "Raydium" },
    { code: "rbn", label: "Ribbon FInance" },
    { code: "ren", label: "renBTC" },
    { code: "rep", label: "Augur" },
    { code: "repv2", label: "REPv2" },
    { code: "req", label: "Request" },
    { code: "reth", label: "Rocket Pool ETH" },
    { code: "rgt", label: "Rari Governance Token" },
    { code: "rif", label: "RIF Token" },
    { code: "rlc", label: "iExec RLC" },
    { code: "rly", label: "Rally" },
    { code: "rndr", label: "Render Token" },
    { code: "rol", label: "Romanian Leu" },
    { code: "ron", label: "Romanian Leu" },
    { code: "rose", label: "Oasis Network" },
    { code: "rpl", label: "Rocket Pool" },
    { code: "rsd", label: "Serbian Dinar" },
    { code: "rune", label: "THORChain (ERC20)" },
    { code: "rvn", label: "Ravencoin" },
    { code: "rwf", label: "Rwandan Franc" },
    { code: "sand", label: "The Sandbox" },
    { code: "sats", label: "Satoshi" },
    { code: "sbd", label: "Solomon Islander Dollar" },
    { code: "sc", label: "Siacoin" },
    { code: "scr", label: "Seychellois Rupee" },
    { code: "sdd", label: "Sudanese Dinar" },
    { code: "sdg", label: "Sudanese Pound" },
    { code: "sek", label: "Swedish Krona" },
    { code: "sfp", label: "SafePal" },
    { code: "sfund", label: "Seedify.fund" },
    { code: "sgd", label: "Singapore Dollar" },
    { code: "shdw", label: "GenesysGo Shadow" },
    { code: "shib", label: "Shiba Inu" },
    { code: "shp", label: "Saint Helenian Pound" },
    { code: "shping", label: "Shping Coin" },
    { code: "sit", label: "Slovenian Tolar" },
    { code: "skk", label: "Slovak Koruna" },
    { code: "skl", label: "SKALE Network" },
    { code: "sle", label: "Sierra Leonean Leone" },
    { code: "sll", label: "Sierra Leonean Leone" },
    { code: "snt", label: "Status Network" },
    { code: "snx", label: "Synthetix Network" },
    { code: "sol", label: "Solana" },
    { code: "sos", label: "Somali Shilling" },
    { code: "spa", label: "Sperax" },
    { code: "spell", label: "Spell Token" },
    { code: "spl", label: "Seborgan Luigino" },
    { code: "srd", label: "Surinamese Dollar" },
    { code: "srg", label: "Surinamese Guilder" },
    { code: "ssv", label: "SSVCoin" },
    { code: "std", label: "Sao Tomean Dobra" },
    { code: "steth", label: "Lido stETH" },
    { code: "stg", label: "Stargate Finance" },
    { code: "stn", label: "Sao Tomean Dobra" },
    { code: "storj", label: "Storj" },
    { code: "strax", label: "Stratis" },
    { code: "stsol", label: "Lido for Solana" },
    { code: "stx", label: "Stacks" },
    { code: "sui", label: "Sui" },
    { code: "suku", label: "SUKU" },
    { code: "super", label: "SuperFarm" },
    { code: "sushi", label: "SushiSwap" },
    { code: "svc", label: "Salvadoran Colon" },
    { code: "swftc", label: "SwftCoin" },
    { code: "sxp", label: "Swipe" },
    { code: "sylo", label: "Sylo" },
    { code: "syn", label: "Synapse" },
    { code: "syp", label: "Syrian Pound" },
    { code: "szl", label: "Swazi Lilangeni" },
    { code: "t", label: "Threshold" },
    { code: "tfuel", label: "Theta Fuel" },
    { code: "thb", label: "Thai Baht" },
    { code: "theta", label: "Theta" },
    { code: "tia", label: "Tianhe" },
    { code: "time", label: "Chrono.tech" },
    { code: "tjs", label: "Tajikistani Somoni" },
    { code: "tkx", label: "Token X" },
    { code: "tmm", label: "Turkmenistani Manat" },
    { code: "tmt", label: "Turkmenistani Manat" },
    { code: "tnd", label: "Tunisian Dinar" },
    { code: "ton", label: "Tokamak Network" },
    { code: "tone", label: "TE-FOOD" },
    { code: "top", label: "Tongan Pa'anga" },
    { code: "trac", label: "OriginTrail" },
    { code: "trb", label: "Tellor" },
    { code: "tribe", label: "Tribe" },
    { code: "tru", label: "TrueFi" },
    { code: "trx", label: "TRON" },
    { code: "try", label: "Turkish Lira" },
    { code: "ttd", label: "Trinidadian Dollar" },
    { code: "ttt", label: "Tap Project" },
    { code: "tusd", label: "True USD" },
    { code: "tvd", label: "Tuvaluan Dollar" },
    { code: "tvk", label: "Terra Virtua Kolect" },
    { code: "twd", label: "Taiwan New Dollar" },
    { code: "twt", label: "Trust Wallet Token" },
    { code: "tzs", label: "Tanzanian Shilling" },
    { code: "uah", label: "Ukrainian Hryvnia" },
    { code: "ugx", label: "Ugandan Shilling" },
    { code: "uma", label: "Universal Market Access" },
    { code: "unfi", label: "Unifi Protocol DAO" },
    { code: "uni", label: "Uniswap" },
    { code: "upi", label: "Pawtocol" },
    { code: "uqc", label: "Uquid Coin" },
    { code: "usdc", label: "USDC" },
    { code: "usdp", label: "USDP Stablecoin" },
    { code: "usdt", label: "Tether" },
    { code: "ust", label: "TerraUSD" },
    { code: "uyu", label: "Uruguayan Peso" },
    { code: "uzs", label: "Uzbekistani Som" },
    { code: "val", label: "Vatican City Lira" },
    { code: "veb", label: "Venezuelan Bolívar" },
    { code: "vef", label: "Venezuelan Bolívar" },
    { code: "ves", label: "Venezuelan Bolívar" },
    { code: "vet", label: "Vechain" },
    { code: "vgx", label: "Voyager Token" },
    { code: "vnd", label: "Vietnamese Dong" },
    { code: "voxel", label: "Voxies" },
    { code: "vtho", label: "VeChainThor" },
    { code: "vuv", label: "Ni-Vanuatu Vatu" },
    { code: "wampl", label: "Wrapped Ampleforth" },
    { code: "waves", label: "Waves" },
    { code: "waxl", label: "Axelar" },
    { code: "waxp", label: "WAX" },
    { code: "wbtc", label: "Wrapped Bitcoin" },
    { code: "wcfg", label: "Wrapped Centrifuge" },
    { code: "wemix", label: "WEMIX" },
    { code: "wluna", label: "Wrapped LUNA" },
    { code: "woo", label: "WOO Network" },
    { code: "wst", label: "Samoan Tala" },
    { code: "xaf", label: "Central African CFA Franc BEAC" },
    { code: "xag", label: "Silver Ounce" },
    { code: "xai", label: "SapienceCoin" },
    { code: "xau", label: "Gold Ounce" },
    { code: "xaut", label: "Tether Gold" },
    { code: "xcd", label: "East Caribbean Dollar" },
    { code: "xch", label: "Chia" },
    { code: "xcn", label: "Chain" },
    { code: "xdc", label: "XDC Network" },
    { code: "xdr", label: "IMF Special Drawing Rights" },
    { code: "xec", label: "Eternal Coin" },
    { code: "xem", label: "NEM" },
    { code: "xlm", label: "Stellar Lumen" },
    { code: "xmon", label: "XMON" },
    { code: "xmr", label: "Monero" },
    { code: "xof", label: "CFA Franc" },
    { code: "xpd", label: "Palladium Ounce" },
    { code: "xpf", label: "CFP Franc" },
    { code: "xpt", label: "Platinum Ounce" },
    { code: "xrd", label: "Radix" },
    { code: "xrp", label: "Ripple" },
    { code: "xtz", label: "Tezos" },
    { code: "xvs", label: "Venus" },
    { code: "xyo", label: "XYO Network" },
    { code: "yer", label: "Yemeni Rial" },
    { code: "yfi", label: "Yearn Finance" },
    { code: "yfii", label: "DFI.Money" },
    { code: "zar", label: "South African Rand" },
    { code: "zec", label: "ZCash" },
    { code: "zen", label: "Horizen" },
    { code: "zil", label: "Zilliqa" },
    { code: "zmk", label: "Zambian Kwacha" },
    { code: "zmw", label: "Zambian Kwacha" },
    { code: "zrx", label: "ZRX 0x" },
    { code: "zwd", label: "Zimbabwean Dollar" },
    { code: "zwl", label: "Zimbabwean Dolla" },
];
